const Cookies = [
    {
        "domain": ".upwork.com",
        "expirationDate": 1725429554.988311,
        "hostOnly": false,
        "httpOnly": true,
        "name": "user_oauth2_slave_access_token",
        "path": "/",
        "sameSite": "None",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "14810bd8.oauth2v2_b009160b6679cd629565a0c198c78d09:1825495666520092672.oauth2v2_932015131c3e266bb45447bc2dc94993"
    },
    {
        "domain": ".upwork.com",
        "expirationDate": 1735346761.835198,
        "hostOnly": false,
        "httpOnly": false,
        "name": "recognized",
        "path": "/",
        "sameSite": "None",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "5ddaea4e"
    },
    {
        "domain": ".upwork.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "country_code",
        "path": "/",
        "sameSite": "None",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "US"
    },
    {
        "domain": ".upwork.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "XSRF-TOKEN",
        "path": "/",
        "sameSite": "None",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "3b18d86c9d5618aa1dd33547b3df3af0"
    },
    {
        "domain": "www.upwork.com",
        "hostOnly": true,
        "httpOnly": false,
        "name": "enabled_ff",
        "path": "/",
        "sameSite": "None",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "!CI10857Air3Dot0,!RMTAir3Offer,!MP16400Air3Migration,air2Dot76,TONB2256Air3Migration,!RMTAir3Talent,!RMTAir3Home,!RMTAir3Offers,CI9570Air2Dot5,!RMTAir3Hired,JPAir3,!CI10270Air2Dot5QTAllocations,!air2Dot76Qt,!SSINavUser,i18nOn,!i18nGA,SSINavUserBpa,CI17409DarkModeUI,CI11132Air2Dot75,!CI12577UniversalSearch,OTBnrOn"
    },
    {
        "domain": ".upwork.com",
        "expirationDate": 1725393203,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_upw_ses.5831",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "*"
    },
    {
        "domain": ".upwork.com",
        "expirationDate": 1733275390,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_cq_duid",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1.1724066862.m4HQ40pzXzHFpq6w"
    },
    {
        "domain": ".upwork.com",
        "expirationDate": 1756948340.746818,
        "hostOnly": false,
        "httpOnly": false,
        "name": "visitor_id",
        "path": "/",
        "sameSite": "None",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "161.123.115.235.1724066858889000"
    },
    {
        "domain": ".upwork.com",
        "expirationDate": 1726745413.488675,
        "hostOnly": false,
        "httpOnly": true,
        "name": "device_view",
        "path": "/",
        "sameSite": "None",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "full"
    },
    {
        "domain": "www.upwork.com",
        "expirationDate": 1725996202.496434,
        "hostOnly": true,
        "httpOnly": false,
        "name": "AWSALBCORS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "Q4BWCxVy7YNVfzj0LR7PKxa8PfFV9NOOBfgP4PBPfnz/cbc+HvuuUs+0iuOI+bjkmJxpS/0GOQzEOYg17FYdGN9zbcgRqJ+PEME/B4OR1TRIshrlVPgKcfSbUvmm"
    },
    {
        "domain": ".upwork.com",
        "expirationDate": 1725433162.488784,
        "hostOnly": false,
        "httpOnly": false,
        "name": "profile_vv_gql_token",
        "path": "/",
        "sameSite": "None",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "oauth2v2_13a878d93adc326ce153263c055ff05a"
    },
    {
        "domain": ".upwork.com",
        "hostOnly": false,
        "httpOnly": true,
        "name": "_cfuvid",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "PAWqGfL2N4VibbNtTo4Dj3r7xxJpkiU09dBic7DGjdQ-1725391393507-0.0.1.1-604800000"
    },
    {
        "domain": ".upwork.com",
        "expirationDate": 1725433154.390672,
        "hostOnly": false,
        "httpOnly": true,
        "name": "c2d10e21sb",
        "path": "/nx/find-work/",
        "sameSite": "None",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "oauth2v2_4004a2f516c9f960ac54dc9b232406da"
    },
    {
        "domain": ".upwork.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "_cq_suid",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "1.1724066862.JEIZK5tuy0V5hDhY"
    },
    {
        "domain": ".upwork.com",
        "expirationDate": 1725473714.709069,
        "hostOnly": false,
        "httpOnly": false,
        "name": "UniversalSearchNuxt_vt",
        "path": "/",
        "sameSite": "None",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "oauth2v2_e053ef7ee388cb480b9f49ae1815de47"
    },
    {
        "domain": ".upwork.com",
        "expirationDate": 1727005261.200351,
        "hostOnly": false,
        "httpOnly": false,
        "name": "uTheme",
        "path": "/",
        "sameSite": "None",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "air-3-0"
    },
    {
        "domain": ".upwork.com",
        "expirationDate": 1725433154.489168,
        "hostOnly": false,
        "httpOnly": true,
        "name": "2de769efsb",
        "path": "/",
        "sameSite": "None",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "oauth2v2_66bf2a3ff2fc9807228e74d377bd4048"
    },
    {
        "domain": ".upwork.com",
        "expirationDate": 1740943303.108497,
        "hostOnly": false,
        "httpOnly": false,
        "name": "umq",
        "path": "/",
        "sameSite": "None",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1920"
    },
    {
        "domain": ".upwork.com",
        "expirationDate": 1759951403.161048,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_upw_id.5831",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "7d5adb6d-f197-45c8-a6e7-872774f42663.1724066862.6.1725391403.1725387395.95ab9a13-0ed9-4123-958b-894275c8506a.de664274-e56d-4fe1-a557-cc8867fcee24.14963b8b-f1bb-45f3-8a21-39ae345a5027.1725390936152.8"
    },
    {
        "domain": ".upwork.com",
        "hostOnly": false,
        "httpOnly": true,
        "name": "master_access_token",
        "path": "/",
        "sameSite": "None",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "14810bd8.oauth2v2_b009160b6679cd629565a0c198c78d09"
    },
    {
        "domain": ".upwork.com",
        "expirationDate": 1725433153.463489,
        "hostOnly": false,
        "httpOnly": true,
        "name": "1e587712sb",
        "path": "/",
        "sameSite": "None",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "oauth2v2_e9a88d6eac6d4a60e5eb4422e3a1b4fa"
    },
    {
        "domain": ".upwork.com",
        "expirationDate": 1725393191.990501,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__cf_bm",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "D7mD5xStb0ISRpPclkDkpW2YAFsepGWfy6fBQHWUuX0-1725391393-1.0.1.1-BXjuVaC2zxxSgRTLbKsPgeD7v1NeQTC8NuebaWU0HADD21wACnkupsYI4AonPS.F7Zm69xD5WvO4wbRVLM1Htw"
    },
    {
        "domain": "www.upwork.com",
        "expirationDate": 1725951553.755433,
        "hostOnly": true,
        "httpOnly": true,
        "name": "__cflb",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "02DiuEXPXZVk436fJfSVuuwDqLqkhavJbLzR38n9vko9M"
    },
    {
        "domain": ".upwork.com",
        "expirationDate": 1733167391,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_rdt_uuid",
        "path": "/",
        "sameSite": "strict",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1724066868035.e9038899-1e1d-4e3b-aa6e-ed67ab21e9ba"
    },
    {
        "domain": "www.upwork.com",
        "expirationDate": 1725990802.046406,
        "hostOnly": true,
        "httpOnly": false,
        "name": "AWSALBTGCORS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "LA6opFRZO3PwWyxQ3c2hWC644QQZItYKszET1SwgjOIUuDYNaXyTgFIdv+ZUXkhwiXuZZBD5sY6oDl+XfKGUl95lxvTGMsHeBm6qCQ/8dZow18VTNuIfrNQGfmUls+bFv20mXUlcMI091exo9rFf3SCiHwhHpPgdWqHfjPWTg4oi"
    },
    {
        "domain": ".upwork.com",
        "expirationDate": 1727983388.746713,
        "hostOnly": false,
        "httpOnly": false,
        "name": "company_last_accessed",
        "path": "/",
        "sameSite": "None",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "d1068688665"
    },
    {
        "domain": "www.upwork.com",
        "hostOnly": true,
        "httpOnly": false,
        "name": "cookie_domain",
        "path": "/",
        "sameSite": "None",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": ".upwork.com"
    },
    {
        "domain": "www.upwork.com",
        "hostOnly": true,
        "httpOnly": false,
        "name": "cookie_prefix",
        "path": "/",
        "sameSite": "None",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": ""
    },
    {
        "domain": ".upwork.com",
        "expirationDate": 1727983388.74676,
        "hostOnly": false,
        "httpOnly": false,
        "name": "current_organization_uid",
        "path": "/",
        "sameSite": "None",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1825495666520092673"
    },
    {
        "domain": ".upwork.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "IR_13634",
        "path": "/",
        "sameSite": "None",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "1725391391237%7C0%7C1725391391237%7C%7C"
    },
    {
        "domain": ".upwork.com",
        "expirationDate": 1758627064.593065,
        "hostOnly": false,
        "httpOnly": false,
        "name": "IR_PI",
        "path": "/",
        "sameSite": "None",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "84ff05d0-5e1e-11ef-894b-791e7b7e2b00%7C1724067011711"
    },
    {
        "domain": ".upwork.com",
        "expirationDate": 1756927402.496495,
        "hostOnly": false,
        "httpOnly": true,
        "name": "spt",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "f75330ed-243c-4f7a-a61f-de3d3a8c5626"
    },
    {
        "domain": ".upwork.com",
        "expirationDate": 1727005261.200692,
        "hostOnly": false,
        "httpOnly": false,
        "name": "uThemeMode",
        "path": "/",
        "sameSite": "None",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "light"
    }
]

export default Cookies;